### ISSUE TITLE
[🪲 BUG]: Updating team name without changing the name causes unnecessary database calls

### ISSUE THREAD

**Issue by ashrafchowdury** [mfts/papermark#189]
## Description
Currently, **it is possible to update the team name without actually changing the name.** This is causing unnecessary database calls, which can impact performance.

## How to prevent it
We need to implement a `logic` to ensure that the name is modified before sending a request to the database upon clicking the `Save changes` button.

## Bug Preview
https://github.com/mfts/papermark/assets/87828904/e0bc3ff0-0e6f-468e-a5d6-da22cb4deee5

**Comment by Aashish-Upadhyay-101** [comment]
<img width="1440" alt="Screenshot 2023-12-05 at 7 16 26 PM" src="https://github.com/mfts/papermark/assets/81024263/b3ff5642-5770-45ec-92d8-37ed3a4ec5fb">


hey @ashrafchowdury the multiple calls that you see in the network tab are due to useSwr's `dedupingInterval` that fetches data every X seconds, if you just hit the save it will call `update-name` and `teams` (teams because to fetch data again with the updated name)

**Comment by Aashish-Upadhyay-101** [comment]
You mean optimistic update? 
then what about the name in the sidebar? 

right now how it is implemented is 

<img width="1440" alt="Screenshot 2023-12-05 at 7 16 26 PM" src="https://github.com/mfts/papermark/assets/81024263/b3ff5642-5770-45ec-92d8-37ed3a4ec5fb">

If you just hit the save it will call `update-name` and `teams` (teams because to fetch data again with the updated name to update the UI in all the places)

**Comment by ashrafchowdury** [comment]
However, the issue is that the `update-name` and `teams` are called even when the name is not changed. It has to be only called when we change the name on the input filed

**Comment by mfts** [comment]
Yes good point @ashrafchowdury, one can click on "Save changes" even if the name is unchanged.

**Comment by ashrafchowdury** [comment]
I would love to work on this issue. Can you please assign this issue to me? @mfts

**Comment by mfts** [comment]
Thanks for volunteering to work on this issue, @ashrafchowdury 💪 

Let us know if there's anything we can help :)

**Comment by Aashish-Upadhyay-101** [comment]
Oh I see, I must have forgotten to validate that part😁
Thanks for catching it !!
