### ISSUE TITLE
refactor password option to show decrypted password for link owners instead of encrypted password

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#380]
This may throw off someone if they want to double check that they set the correct password and then see a long encrypted string of text

**Comment by varunguleriaCodes** [comment]
Hey @mfts , I am looking into this issue. Found that we are hashing the password instead of encrypting. Since a hashed password can't be decrypted only compared. We need to use something like crypto module(for encryption - decryption) or a popup to compare the passwords rather than directly displaying it. What is your take on this?

**Comment by mfts** [comment]
Hey @varunguleriaCodes that's a really good point. Yea indeed that would solve the problem. 

Do you want to work in this?

**Comment by varunguleriaCodes** [comment]
Hey @mfts sure, just which approach should I follow:
1. Crypto Module or 2.Popup to compare passwords ?

**Comment by mfts** [comment]
Let's go with the `crypto` approach. It's cleaner.
