### ISSUE TITLE
Signing Documents?

### ISSUE THREAD

**Issue by mv-stns** [mfts/papermark#582]
Hey there, I just wanted to ask if papermark.io supports signing documents digitally? Nowhere on the website, not even in the FAQ section, mentions any features like that, but comparing itself directly as a DocSend alternative

**Comment by mfts** [comment]
Hey @mv-stns we are not supporting digital signatures yet. 

Our friends at Documenso are building open source signing primitives and once that is done, we plan to implement it into Papermark.

**Comment by mv-stns** [comment]
Sounds phenomenal! Okay, just thought about those friends! I can wait until then! Thank you very much!

**Comment by TyceHerrman** [comment]
@mfts any updates on this and whether Documenso is developed enough for implementation?

**Comment by 16it-pl** [comment]
Hey @mfts @TyceHerrman - this thread has been quiet for a year, so I'll offer a concrete option rather than just another bump.

We're **[Autosignly](https://autosignly.eu)**, a small European team building an e-signature API. Not trying to replace the Documenso plan - just noting that if the blocker is *"signing primitives aren't ready yet"*, an API might get you there faster than embedding a whole signing stack.

What's relevant for Papermark specifically:

- **Pay-as-you-go, no subscription.** Signatures from $0.01, sandboxes free. Nobody has to buy a seat plan to sign one document after a data room visit, which matters because the NDA flow today is one-click *acceptance*, and turning that into an actual signature shouldn't force users onto a second vendor's contract.
- **Stable API (v1.0.0) with open-source SDKs**, including Node/TypeScript - same stack as Papermark. Create a document, send it for signature, receive webhooks (`completed` / `declined` / `expired`), pull the signed PDF.
- **Local webhook client**, so the whole flow runs on localhost without tunnels. Self-hosters can test it end to end.
- We cover the eIDAS signature levels, including qualified (currently available in Poland, expanding across the EU). For the plain e-signature case it's country-agnostic.

| | |
|---|---|
| Docs | https://docs.16it.eu/docs/autosignly/integrations/api |
| SDK | https://github.com/16it-pl/autosignly-sdk |
| Site | https://autosignly.eu |

Free sandboxes are available right after signup, so anyone can run the full flow without talking to us first.

Happy to answer questions, or to contribute the integration ourselves if there's interest.
