### ISSUE TITLE
Disable individual visits from total document / link statistics

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#96]
Configure document / link analytics to select / deselect individual visits or links which are counting towards the total.

Reported by a user, if one visitor stays super long, it messes up the overall analytics
<img width="640" alt="PastedGraphic-1" src="https://github.com/mfts/papermark/assets/4049052/f8d4b577-d283-429d-8ab4-ca76ae395d5c">

**Comment by RockingThor** [comment]
Can you please assign this issue to me? Would love to fix this.

**Comment by mfts** [comment]
Hey @RockingThor would love for you to work on this. 

The data comes from tinybird. So we probably need to create a new pipe. See current implementation `lib/tinybird/endpoints`

**Comment by vndpal** [comment]
Hi @mfts , I have almost completed this, will raise a PR later today as currently, my daily Tinybird allowed limit is exceeded :(. Once the limit gets renewed I will test it and raise the PR.
For now, instead of creating a new pipe I modified the existing pipe with Version no 2.

@RockingThor I can share with you a few "Good First Issues" to get you started, this particular issue requires an understanding of tinybird Apis, and may not be a good issue for someone new to the repo.

**Comment by mfts** [comment]
Awesome @vndpal that's so great to hear!

**Comment by RockingThor** [comment]
That would be awesome if you could share some good first issues with me @vndpal

**Comment by vndpal** [comment]
@RockingThor as promised, created an easy issue for you #126 . let me know if you any help. Good luck :)

**Comment by mfts** [comment]
Wow this issue has been sitting here for a while. Thanks to the work of @vndpal and others it's closed #318
