### ISSUE TITLE
[🕹️]side quest: Gif Magic (150 Points)

### ISSUE THREAD

**Issue by Naprila** [mfts/papermark#986]
### What side quest or challenge are you solving?

Create a branded gif related to Papermark.

### Points

150

### Description

Created a branded gif related to Papermark

### Provide proof that you've completed the task

https://media.giphy.com/media/3DtSltRWbT9NWziduJ/giphy.gif

<img width="1320" alt="Screenshot 2024-10-15 at 12 30 08 AM" src="https://github.com/user-attachments/assets/c1c80fa6-b6b3-41c1-bd94-7aa23379323b">

**Comment by AadiJainTikamgarh** [comment]
## Created a GIF related to papermark

### Description
Promoting the use to papermark to share document instead of any other services.

### Proof of completion of Task
https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExemVkbjlic2o2YWFsdTdkYWRuazhvdmJmamhlMDhyNW9tYzdrZXV5NSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/eKQaql40T65YdL7Irz/giphy.gif
